import './bootstrap';
import './modal';
import './search-filter';
import './confirm';
import './grade-verify';
import './verify-all-remaining';
import './intervention-delivery';
import './group-delivery';
import './auth';